### ISSUE TITLE
hasClient的Room继承问题

### ISSUE THREAD

**Issue by pb57124** [sdkbb2007/mahjongGame_by_Kbengine_unity#3]
服务器源码Room类，具备客户端(hasClient="true")，然而Room的Base类创建，继承自KBEngine.Entity,而不是继承自KBEngine.Proxy。
    有在官方论坛请教过Kbe，“baseapp上只有Proxy会同步到客户端，只有Proxy拥有客户端”。请问这里是否正确处理是否应该继承自Proxy，或者继承自KBEngine.Entity也是没有问题的呢？

Link:
https://bbs.comblockengine.com/forum.php?mod=viewthread&tid=6974&extra=page%3D1

**Comment by sdkbb2007** [comment]
拥有客户端 我是这么理解的 ： 可以和服务器建立通讯 就是用客户端来控制服务器上的实体，Proxy翻译过来是代理人的意思  继承它 就相当于在服务器上创建一个代理人来和客户端通讯 。房间因为不需要这个代理，因为他不是玩家，不接受玩家控制，所以不需要代理，但是需要让他被其他客户端玩家看到所以要hasClient="true"
